import { Schema, model, ref } from "./helpers.js";

export const Booking = model("Booking", {
  quote: { type: Schema.Types.ObjectId, ref: "Quote", unique: true, sparse: true, required: false },
  request: { type: Schema.Types.ObjectId, ref: "Request", required: false },
  listing: ref("Listing"),
  provider: ref("BusinessProfile"),
  seeker: { type: Schema.Types.ObjectId, ref: "BusinessProfile", required: false },
  itemIndex: Number,
  start: Date,
  end: Date,
  quantity: Number,
  price: Number,
  deposit: Number,
  commission: Number,
  conditions: String,
  logistics: String,
  cancellationHours: Number,
  cancellationReason: String,
  status: {
    type: String,
    enum: ["confirmed", "in_progress", "completed", "cancelled"],
    default: "confirmed",
  },
  isOfflineDeal: { type: Boolean, default: false },
  offlineClient: {
    name: String,
    phone: String,
    email: String,
    notes: String,
  },
  returnedAt: Date,
  reminderSent: Boolean,
  returnReminderSent: Boolean,
  expiryNotifiedAt: Date,
});
