export const agentCatalog = [
  { id: "parser", title: "Brief interpreter", role: "seeker", href: "/dashboard/planner", description: "Convert an event brief into editable requirements and explicit clarification questions.", engine: "Gemini · structured output", check: "Category allowlist, bounded quantities and human review" },
  { id: "bundle", title: "Availability planner", role: "seeker", href: "/dashboard/planner", description: "Retrieve compatible inventory for independent requirements in parallel.", engine: "MongoDB · deterministic search", check: "Dates, minimum rental, quantity, distance and delivery" },
  { id: "conductor", title: "Event Conductor", role: "seeker", href: "/dashboard/planner", description: "Allocate shared stock, compare packages and test supplier-removal recovery.", engine: "LangGraph · bounded optimization", check: "Constraint evidence, revalidation and versioned review" },
  { id: "ranking", title: "Ranking explainer", role: "seeker", href: "/dashboard/agents#matching", description: "Explain computed matches, supply gaps and trade-offs without changing scores.", engine: "Gemini · evidence-based advice", check: "Computed matches remain available if commentary fails" },
  { id: "knowledge", title: "Resource researcher", role: "both", href: "/dashboard/agents", description: "Combine semantic and keyword retrieval into answers with listing citations.", engine: "Hugging Face · hybrid RAG", check: "Every claim references a retrieved source ID; dates need a separate search" },
  { id: "negotiation", title: "Negotiation advisor", role: "both", href: "/dashboard/negotiations", description: "Use your private quote history to suggest specific, reviewable trade-offs.", engine: "Gemini · MongoDB checkpoints", check: "Participant authorization and separate party memory" },
  { id: "tone", title: "Communication coach", role: "both", href: "/dashboard/negotiations", description: "Review recent message tone and suggest constructive next steps.", engine: "Gemini · structured classification", check: "One label per message; no personality or intent profiling" },
  { id: "pricing", title: "Pricing advisor", role: "provider", href: "/dashboard/smart-pricing", description: "Compare observed asking prices by rental unit with visible sample sizes.", engine: "Gemini · aggregated market evidence", check: "Sparse-data gates, moderated-listing exclusion and local comparisons" },
  { id: "demand", title: "Demand analyst", role: "provider", href: "/dashboard/forecast", description: "Translate current demand and recorded utilization into suggested opportunities.", engine: "LangGraph · marketplace aggregations", check: "Snapshot observations are distinguished from predictions" },
  { id: "urgency", title: "Urgency advisor", role: "seeker", href: "/dashboard/requests", description: "Prioritize open requests using time, least-covered items and competing demand.", engine: "Deterministic scoring · Gemini explanation", check: "Transparent formula; score survives commentary failure" },
  { id: "insights", title: "Provider digest", role: "provider", href: "/dashboard", description: "Summarize persisted provider activity in a scheduled daily digest.", engine: "Gemini · scheduled workflow", check: "Observed metrics only; no invented earnings" },
  { id: "operations", title: "Operations copilot", role: "admin", href: "/admin/agents", description: "Turn verification, dispute and moderation queue counts into a review brief.", engine: "Gemini · aggregate-only context", check: "No private KYC documents, automatic approvals or adjudication" },
];
